name: net_player_next
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  crypto: ^3.0.3
  fluent_ui: ^4.5.1
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
