name: netplayer_next
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  fluent_ui: ^4.8.5
  flutter:
    sdk: flutter
  flutter_platform_alert: ^0.5.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
